steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_IMAGE_NAME}/newapp', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_IMAGE_NAME}/newapp']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      
            'run',
            'deploy',
            'newapp',
           '--image', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_IMAGE_NAME}/newapp',
            '--region',
            'us-central1',
            '--allow-unauthenticated'
          ]
    
substitutions:
   _IMAGE_NAME: newapp
   _PROJECT_ID: inggage-primary

options:
  logging: CLOUD_LOGGING_ONLY  # or NONE


timeout: '1600s'
