steps:
 # Step 1: Install dependencies
  - name: 'node:14'  # Use the official Node.js image
    entrypoint: 'npm'
    args: ['install']


    # Step 3: Deploy to Google App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'  # Use Google Cloud SDK to deploy
    entrypoint: 'gcloud'
    args: ['app', 'deploy', '--quiet']
options:
  logging: CLOUD_LOGGING_ONLY  # or NONE


timeout: '1600s'


 
